import { useMemo } from "react";
import Layout from "../../components/layout/Layout";
import { useBillingData } from "../../context/BillingDataContext";

function Reports() {
  const {
    billingData,
    billingInfo,
    anomalies,
  } = useBillingData();

  /*
   * --------------------------------------------------
   * Calculate report information
   * --------------------------------------------------
   */

  const totalCost = useMemo(() => {
    return billingData.reduce(
      (sum, item) => sum + Number(item.Cost || 0),
      0
    );
  }, [billingData]);

  const totalRecords = billingData.length;

  const anomalyCount = anomalies.length;

  /*
   * Estimate potential savings.
   *
   * This uses the same temporary 15% estimate
   * currently used by the Dashboard.
   */

  const estimatedSavings = totalCost * 0.15;

  /*
   * --------------------------------------------------
   * Provider summary
   * --------------------------------------------------
   */

  const providerSummary = useMemo(() => {
    const totals = {};

    billingData.forEach((item) => {
      const provider = item.Provider || "Unknown";
      const cost = Number(item.Cost || 0);

      totals[provider] =
        (totals[provider] || 0) + cost;
    });

    return Object.entries(totals)
      .map(([provider, cost]) => ({
        provider,
        cost,
      }))
      .sort((a, b) => b.cost - a.cost);
  }, [billingData]);

  /*
   * --------------------------------------------------
   * Service summary
   * --------------------------------------------------
   */

  const serviceSummary = useMemo(() => {
    const totals = {};

    billingData.forEach((item) => {
      const service = item.Service || "Unknown";
      const cost = Number(item.Cost || 0);

      totals[service] =
        (totals[service] || 0) + cost;
    });

    return Object.entries(totals)
      .map(([service, cost]) => ({
        service,
        cost,
      }))
      .sort((a, b) => b.cost - a.cost);
  }, [billingData]);

  /*
   * --------------------------------------------------
   * Export report
   * --------------------------------------------------
   */

  const exportReport = () => {
    if (billingData.length === 0) {
      return;
    }

    const report = {
      report_title: "CloudSense AI Cloud Cost Report",
      generated_at: new Date().toISOString(),

      summary: {
        total_cost: Number(totalCost.toFixed(2)),
        total_records: totalRecords,
        anomaly_count: anomalyCount,
        estimated_savings: Number(
          estimatedSavings.toFixed(2)
        ),
      },

      provider_summary: providerSummary,

      service_summary: serviceSummary,

      anomalies: anomalies,

      billing_data: billingData,
    };

    const blob = new Blob(
      [JSON.stringify(report, null, 2)],
      {
        type: "application/json",
      }
    );

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;
    link.download = "cloudsense-ai-report.json";

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  /*
   * --------------------------------------------------
   * No billing data
   * --------------------------------------------------
   */

  if (!billingData || billingData.length === 0) {
    return (
      <Layout>

        <div className="mb-8">
          <h1 className="text-3xl font-bold text-slate-900">
            Reports
          </h1>

          <p className="mt-2 text-slate-500">
            Generate a detailed cloud cost analysis report.
          </p>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center shadow-sm">

          <div className="text-5xl">
            📊
          </div>

          <h2 className="mt-4 text-xl font-bold text-slate-800">
            No billing data available
          </h2>

          <p className="mt-2 text-sm text-slate-500">
            Upload a billing CSV file to generate your
            CloudSense AI report.
          </p>

        </div>

      </Layout>
    );
  }

  return (
    <Layout>

      {/* --------------------------------------------------
          Header
      -------------------------------------------------- */}

      <div className="mb-8 flex flex-wrap items-center justify-between gap-4">

        <div>
          <h1 className="text-3xl font-bold text-slate-900">
            Reports
          </h1>

          <p className="mt-2 text-slate-500">
            Detailed cloud cost analysis generated by CloudSense AI.
          </p>
        </div>

        <button
          onClick={exportReport}
          className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700"
        >
          Export Report
        </button>

      </div>

      {/* --------------------------------------------------
          Summary Cards
      -------------------------------------------------- */}

      <div className="mb-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4">

        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <p className="text-sm text-slate-500">
            Total Cloud Cost
          </p>

          <p className="mt-2 text-3xl font-bold text-slate-900">
            ${totalCost.toLocaleString(undefined, {
              maximumFractionDigits: 2,
            })}
          </p>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <p className="text-sm text-slate-500">
            Billing Records
          </p>

          <p className="mt-2 text-3xl font-bold text-slate-900">
            {totalRecords.toLocaleString()}
          </p>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <p className="text-sm text-slate-500">
            Detected Anomalies
          </p>

          <p className="mt-2 text-3xl font-bold text-red-600">
            {anomalyCount}
          </p>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <p className="text-sm text-slate-500">
            Estimated Savings
          </p>

          <p className="mt-2 text-3xl font-bold text-emerald-600">
            ${estimatedSavings.toLocaleString(undefined, {
              maximumFractionDigits: 0,
            })}
          </p>
        </div>

      </div>

      {/* --------------------------------------------------
          Provider Summary
      -------------------------------------------------- */}

      <div className="mb-8 rounded-2xl border border-slate-200 bg-white shadow-sm">

        <div className="border-b border-slate-200 p-6">

          <h2 className="text-xl font-bold text-slate-900">
            Cloud Provider Summary
          </h2>

          <p className="mt-1 text-sm text-slate-500">
            Total spending by cloud provider.
          </p>

        </div>

        <div className="overflow-x-auto">

          <table className="w-full text-left text-sm">

            <thead className="bg-slate-50">

              <tr>
                <th className="px-6 py-4 font-semibold text-slate-600">
                  Provider
                </th>

                <th className="px-6 py-4 font-semibold text-slate-600">
                  Cost
                </th>

                <th className="px-6 py-4 font-semibold text-slate-600">
                  Share
                </th>
              </tr>

            </thead>

            <tbody>

              {providerSummary.map((item) => {

                const percentage =
                  totalCost > 0
                    ? (item.cost / totalCost) * 100
                    : 0;

                return (
                  <tr
                    key={item.provider}
                    className="border-t border-slate-100"
                  >

                    <td className="px-6 py-4 font-semibold text-slate-800">
                      {item.provider}
                    </td>

                    <td className="px-6 py-4">
                      ${item.cost.toLocaleString(undefined, {
                        maximumFractionDigits: 2,
                      })}
                    </td>

                    <td className="px-6 py-4">
                      {percentage.toFixed(1)}%
                    </td>

                  </tr>
                );
              })}

            </tbody>

          </table>

        </div>

      </div>

      {/* --------------------------------------------------
          Service Summary
      -------------------------------------------------- */}

      <div className="mb-8 rounded-2xl border border-slate-200 bg-white shadow-sm">

        <div className="border-b border-slate-200 p-6">

          <h2 className="text-xl font-bold text-slate-900">
            Service Cost Summary
          </h2>

          <p className="mt-1 text-sm text-slate-500">
            Spending distribution across cloud services.
          </p>

        </div>

        <div className="overflow-x-auto">

          <table className="w-full text-left text-sm">

            <thead className="bg-slate-50">

              <tr>
                <th className="px-6 py-4 font-semibold text-slate-600">
                  Service
                </th>

                <th className="px-6 py-4 font-semibold text-slate-600">
                  Cost
                </th>

                <th className="px-6 py-4 font-semibold text-slate-600">
                  Share
                </th>
              </tr>

            </thead>

            <tbody>

              {serviceSummary.map((item) => {

                const percentage =
                  totalCost > 0
                    ? (item.cost / totalCost) * 100
                    : 0;

                return (
                  <tr
                    key={item.service}
                    className="border-t border-slate-100"
                  >

                    <td className="px-6 py-4 font-semibold text-slate-800">
                      {item.service}
                    </td>

                    <td className="px-6 py-4">
                      ${item.cost.toLocaleString(undefined, {
                        maximumFractionDigits: 2,
                      })}
                    </td>

                    <td className="px-6 py-4">
                      {percentage.toFixed(1)}%
                    </td>

                  </tr>
                );
              })}

            </tbody>

          </table>

        </div>

      </div>

      {/* --------------------------------------------------
          Anomaly Summary
      -------------------------------------------------- */}

      <div className="mb-8 rounded-2xl border border-slate-200 bg-white shadow-sm">

        <div className="border-b border-slate-200 p-6">

          <h2 className="text-xl font-bold text-slate-900">
            Anomaly Summary
          </h2>

          <p className="mt-1 text-sm text-slate-500">
            Billing records identified by the Isolation Forest model.
          </p>

        </div>

        {anomalies.length === 0 ? (

          <div className="p-8 text-center">

            <p className="font-semibold text-green-600">
              No anomalies detected
            </p>

            <p className="mt-1 text-sm text-slate-500">
              The current billing dataset does not contain
              detected unusual spending patterns.
            </p>

          </div>

        ) : (

          <div className="overflow-x-auto">

            <table className="w-full text-left text-sm">

              <thead className="bg-slate-50">

                <tr>

                  <th className="px-6 py-4 font-semibold text-slate-600">
                    Date
                  </th>

                  <th className="px-6 py-4 font-semibold text-slate-600">
                    Provider
                  </th>

                  <th className="px-6 py-4 font-semibold text-slate-600">
                    Service
                  </th>

                  <th className="px-6 py-4 font-semibold text-slate-600">
                    Cost
                  </th>

                  <th className="px-6 py-4 font-semibold text-slate-600">
                    Severity
                  </th>

                </tr>

              </thead>

              <tbody>

                {anomalies.map((item, index) => (

                  <tr
                    key={`${item.Date}-${item.Service}-${index}`}
                    className="border-t border-slate-100"
                  >

                    <td className="px-6 py-4">
                      {item.Date}
                    </td>

                    <td className="px-6 py-4 font-medium">
                      {item.Provider}
                    </td>

                    <td className="px-6 py-4">
                      {item.Service}
                    </td>

                    <td className="px-6 py-4 font-semibold">
                      ${Number(
                        item.Cost || 0
                      ).toLocaleString()}
                    </td>

                    <td className="px-6 py-4">

                      <span
                        className={`rounded-full px-3 py-1 text-xs font-semibold ${
                          item.severity === "Critical"
                            ? "bg-red-100 text-red-700"
                            : item.severity === "High"
                            ? "bg-orange-100 text-orange-700"
                            : item.severity === "Medium"
                            ? "bg-yellow-100 text-yellow-700"
                            : "bg-green-100 text-green-700"
                        }`}
                      >
                        {item.severity || "Unknown"}
                      </span>

                    </td>

                  </tr>

                ))}

              </tbody>

            </table>

          </div>

        )}

      </div>

      {/* --------------------------------------------------
          Report Information
      -------------------------------------------------- */}

      <div className="rounded-2xl border border-blue-200 bg-blue-50 p-6">

        <h2 className="font-bold text-blue-800">
          CloudSense AI Report
        </h2>

        <p className="mt-2 text-sm leading-6 text-blue-700">
          This report combines billing analysis, cloud provider
          spending, service-level costs, anomaly detection, and
          estimated optimization opportunities.
        </p>

        {billingInfo?.filename && (
          <p className="mt-3 text-xs text-blue-600">
            Source file:{" "}
            <span className="font-semibold">
              {billingInfo.filename}
            </span>
          </p>
        )}

      </div>

    </Layout>
  );
}

export default Reports;